# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='export',
            old_name='user',
            new_name='created_by',
        ),
    ]
