# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0003_task_is_questions_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
