# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0003_auto_20160622_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
