# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0004_auto_20160706_1148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterField(
            model_name='export',
            name='export_file',
            field=models.FileField(blank=True, null=True, upload_to='exports/%Y/%m/%d/%H%M%S%f/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='csv',
            field=models.FileField(upload_to='tasks/%Y/%m/%d/%H%M%S%f/'),
        ),
    ]
