# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0004_question_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='closed_on',
        ),
    ]
