# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0005_remove_task_closed_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_best_of',
            field=models.BooleanField(default=False, help_text='Check this if you want to run best-of-n. Default: max-of-n'),
        ),
    ]
