# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 07:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0005_auto_20160707_0751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='export',
            options={'ordering': ['-created_on']},
        ),
    ]
