# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0006_auto_20160708_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_multiple_choice',
            field=models.BooleanField(default=False),
        ),
    ]
