# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0007_task_answer_plugin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_file', models.FileField(upload_to='exports/%Y/%m/%d/')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasker.Task')),
            ],
        ),
    ]
